version: '3'
services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    environment:
      POSTGRES_USER: YOUR_USERNAME
      POSTGRES_PASSWORD: YOUR_PASSWORD
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
  demo-1:
    build: .
    container_name: demo-1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/YOUR_DB
      SPRING_DATASOURCE_USERNAME: YOUR_USERNAME
      SPRING_DATASOURCE_PASSWORD: YOUR_PASSWORD
    depends_on:
      - postgres
    ports:
      - "8080:8080"